FROM rust:1.60.0-slim-buster

WORKDIR /app
COPY . /app

RUN apt-get update && \
    apt-get install -y cmake build-essential && \
    rustup component add rustfmt && \
    cargo build --release

ENTRYPOINT ["./target/release/server", "--pair", "sol-usdt"]
